.TH "src/GLFWManager.cpp" 3 "Martes, 26 de Mayo de 2015" "Picking" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/GLFWManager.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <GL/glew\&.h>\fP
.br
\fC#include 'Headers/GLFWManager\&.h'\fP
.br
\fC#include 'Headers/Main\&.h'\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBGLApplication\fP * \fBapplication\fP"
.br
.ti -1c
.RI "\fBPicking::Picking\fP * \fBpicking\fP"
.br
.ti -1c
.RI "\fBCamera\fP * \fBpCamera\fP"
.br
.in -1c
.SH "Documentación de las funciones"
.PP 
.SS "int main ()"

.PP
Definición en la línea 9 del archivo GLFWManager\&.cpp\&.
.PP
Hace referencia a WindowManager::GetInputManager(), GLApplication::GLMain(), Picking::Picking::SetCamera(), InputManager::SetCamera(), GLApplication::SetCamera(), GLApplication::SetPicking() y GLApplication::SetWindowManager()\&.
.SH "Documentación de las variables"
.PP 
.SS "\fBGLApplication\fP* application"

.PP
Definición en la línea 5 del archivo GLFWManager\&.cpp\&.
.SS "\fBCamera\fP* pCamera"

.PP
Definición en la línea 7 del archivo GLFWManager\&.cpp\&.
.PP
Referenciado por InputManager::SetCamera(), GLApplication::SetCamera() y Model::SetCamera()\&.
.SS "\fBPicking::Picking\fP* picking"

.PP
Definición en la línea 6 del archivo GLFWManager\&.cpp\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Picking del código fuente\&.
