.TH "src/Headers/GLFWManager.h" 3 "Martes, 26 de Mayo de 2015" "Picking" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Headers/GLFWManager.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <GLFW/glfw3\&.h>\fP
.br
\fC#include 'WindowManager\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBGLFWManager\fP"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Picking del código fuente\&.
