.TH "Light::Light" 3 "Martes, 26 de Mayo de 2015" "Picking" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Light::Light \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Light\&.h>\fP
.SS "M茅todos p煤blicos"

.in +1c
.ti -1c
.RI "\fBLight\fP ()"
.br
.ti -1c
.RI "void \fBSetLight\fP (\fBLightAtrr\fP *\fBlightAtrr\fP)"
.br
.ti -1c
.RI "virtual \fB~Light\fP ()"
.br
.in -1c
.SS "Atributos privados"

.in +1c
.ti -1c
.RI "\fBLightAtrr\fP * \fBlightAtrr\fP"
.br
.in -1c
.SH "Descripci贸n detallada"
.PP 
Clase para la iluminaci髇\&. 
.PP
Definici贸n en la l铆nea 27 del archivo Light\&.h\&.
.SH "Documentaci贸n del constructor y destructor"
.PP 
.SS "Light::Light::Light ()"
Constructor default\&. 
.PP
Definici贸n en la l铆nea 15 del archivo Light\&.cpp\&.
.SS "Light::Light::~Light ()\fC [virtual]\fP"
Destructor de clase\&. 
.PP
Definici贸n en la l铆nea 18 del archivo Light\&.cpp\&.
.SH "Documentaci贸n de las funciones miembro"
.PP 
.SS "void Light::Light::SetLight (\fBLightAtrr\fP *lightAtrr)"
Setter de atributos de la liluminaci髇\&. 
.PP
\fBPar谩metros:\fP
.RS 4
\fIlightAtrr\fP Par醡etros de iluminaci髇\&. 
.RE
.PP

.PP
Definici贸n en la l铆nea 25 del archivo Light\&.cpp\&.
.SH "Documentaci贸n de los datos miembro"
.PP 
.SS "\fBLightAtrr\fP* Light::Light::lightAtrr\fC [private]\fP"

.PP
Definici贸n en la l铆nea 43 del archivo Light\&.h\&.

.SH "Autor"
.PP 
Generado autom谩ticamente por Doxygen para Picking del c贸digo fuente\&.
