.TH "Picking" 3 "Martes, 26 de Mayo de 2015" "Picking" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Picking \- 
.SH SYNOPSIS
.br
.PP
.SS "Clases"

.in +1c
.ti -1c
.RI "struct \fBClick\fP"
.br
.ti -1c
.RI "class \fBMark\fP"
.br
.ti -1c
.RI "class \fBPicking\fP"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Picking del código fuente\&.
