.TH "src/Picking.cpp" 3 "Martes, 26 de Mayo de 2015" "Picking" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Picking.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Headers/Picking\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBPicking\fP"
.br
.in -1c
.SS "'defines'"

.in +1c
.ti -1c
.RI "#define \fBEPSILON\fP   0\&.000001"
.br
.in -1c
.SH "Documentación de los 'defines'"
.PP 
.SS "#define EPSILON   0\&.000001"

.PP
Definición en la línea 10 del archivo Picking\&.cpp\&.
.PP
Referenciado por Picking::Picking::RayTriangleIntersect()\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Picking del código fuente\&.
