.TH "Referencia del directorio src/Headers" 3 "Martes, 26 de Mayo de 2015" "Origami" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio src/Headers \- 
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBCamera\&.h\fP"
.br
.ti -1c
.RI "archivo \fBGLFWManager\&.h\fP"
.br
.ti -1c
.RI "archivo \fBInputManager\&.h\fP"
.br
.ti -1c
.RI "archivo \fBLight\&.h\fP"
.br
.ti -1c
.RI "archivo \fBLightingTechnique\&.h\fP"
.br
.ti -1c
.RI "archivo \fBMain\&.h\fP"
.br
.ti -1c
.RI "archivo \fBModel\&.h\fP"
.br
.ti -1c
.RI "archivo \fBShader\&.h\fP"
.br
.ti -1c
.RI "archivo \fBTexture\&.h\fP"
.br
.ti -1c
.RI "archivo \fBTimeManager\&.h\fP"
.br
.ti -1c
.RI "archivo \fBUtil\&.h\fP"
.br
.ti -1c
.RI "archivo \fBWindowManager\&.h\fP"
.br
.in -1c
