.TH "src/InputManager.cpp" 3 "Martes, 26 de Mayo de 2015" "Origami" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/InputManager.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Headers/InputManager\&.h'\fP
.br
\fC#include 'Headers/TimeManager\&.h'\fP
.br

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Origami del código fuente\&.
