.TH "Light" 3 "Martes, 26 de Mayo de 2015" "Origami" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Light \- 
.SH SYNOPSIS
.br
.PP
.SS "Clases"

.in +1c
.ti -1c
.RI "struct \fBLightAtrr\fP"
.br
.ti -1c
.RI "class \fBLight\fP"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Origami del código fuente\&.
