.TH "src/Headers/Light.h" 3 "Martes, 26 de Mayo de 2015" "Origami" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Headers/Light.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <glm/glm\&.hpp>\fP
.br
\fC#include <glm/gtc/type_ptr\&.hpp>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "struct \fBLight::LightAtrr\fP"
.br
.ti -1c
.RI "class \fBLight::Light\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBLight\fP"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Origami del código fuente\&.
