.TH "src/LightingTechnique.cpp" 3 "Martes, 26 de Mayo de 2015" "Origami" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/LightingTechnique.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Headers/LightingTechnique\&.h'\fP
.br

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Origami del código fuente\&.
