.TH "src/Headers/LightingTechnique.h" 3 "Martes, 26 de Mayo de 2015" "Origami" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Headers/LightingTechnique.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <GL/glew\&.h>\fP
.br
\fC#include 'Shader\&.h'\fP
.br
\fC#include 'Light\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBLightingTechnique\fP"
.br
.ti -1c
.RI "struct \fBLightingTechnique::m_light\fP"
.br
.in -1c
.SS "'defines'"

.in +1c
.ti -1c
.RI "#define \fBLIGHTING_TECHNIQUE_H\fP"
.br
.in -1c
.SH "Documentación de los 'defines'"
.PP 
.SS "#define LIGHTING_TECHNIQUE_H"

.PP
Definición en la línea 10 del archivo LightingTechnique\&.h\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Origami del código fuente\&.
