.TH "src/Texture.cpp" 3 "Martes, 26 de Mayo de 2015" "Origami" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Texture.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Headers/Texture\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBTexture\fP"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Origami del código fuente\&.
