.TH "src/Light.cpp" 3 "Martes, 26 de Mayo de 2015" "Pistasdeprofunidad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Light.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Headers/Light\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBLight\fP"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Pistasdeprofunidad del código fuente\&.
