.TH "src/Headers/RayCasting.h" 3 "Martes, 26 de Mayo de 2015" "Pistasdeprofunidad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Headers/RayCasting.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'Model\&.h'\fP
.br
\fC#include 'Main\&.h'\fP
.br
\fC#include 'Util\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "struct \fBTestObjectHit\fP"
.br
.ti -1c
.RI "class \fBRayCasting::RayCasting\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBRayCasting\fP"
.br
.in -1c
.SS "Enumeraciones"

.in +1c
.ti -1c
.RI "enum \fBTypeObjectBox\fP { \fBBox\fP, \fBSphere\fP }"
.br
.in -1c
.SH "Documentación de las enumeraciones"
.PP 
.SS "enum \fBTypeObjectBox\fP"
Enum para el typo de boundig box que envuelce al objeto\&. 
.PP
\fBValores de enumeraciones\fP
.in +1c
.TP
\fB\fIBox \fP\fP
Box\&. 
.TP
\fB\fISphere \fP\fP
Sphere\&. 
.PP
Definición en la línea 19 del archivo RayCasting\&.h\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Pistasdeprofunidad del código fuente\&.
