.TH "src/Headers/Camera.h" 3 "Martes, 26 de Mayo de 2015" "CubeRubick" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Headers/Camera.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <glm/glm\&.hpp>\fP
.br
\fC#include <glm/gtc/matrix_transform\&.hpp>\fP
.br
\fC#include <glm/gtx/transform2\&.hpp>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBCamera\fP"
.br
.in -1c
.SS "'defines'"

.in +1c
.ti -1c
.RI "#define \fBPI\fP   3\&.14159265358979323846264338327950288"
.br
.ti -1c
.RI "#define \fBGLM_FORCE_RADIANS\fP"
.br
.in -1c
.SH "Documentación de los 'defines'"
.PP 
.SS "#define GLM_FORCE_RADIANS"

.PP
Definición en la línea 5 del archivo Camera\&.h\&.
.SS "#define PI   3\&.14159265358979323846264338327950288"

.PP
Definición en la línea 4 del archivo Camera\&.h\&.
.PP
Referenciado por Camera::SetViewByMouse()\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para CubeRubick del código fuente\&.
