.TH "src/Headers/Main.h" 3 "Martes, 26 de Mayo de 2015" "CubeRubick" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Headers/Main.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'WindowManager\&.h'\fP
.br
\fC#include 'Model\&.h'\fP
.br
\fC#include 'TimeManager\&.h'\fP
.br
\fC#include 'Camera\&.h'\fP
.br
\fC#include 'InputManager\&.h'\fP
.br
\fC#include 'RubiksCube\&.h'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBGLApplication\fP"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para CubeRubick del código fuente\&.
