.TH "src/Main.cpp" 3 "Martes, 26 de Mayo de 2015" "CubeRubick" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <GL/glew\&.h>\fP
.br
\fC#include 'Headers/Main\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBModel\fP \fBg_cube\fP"
.br
.ti -1c
.RI "\fBVertex3\fP \fBvertices1\fP []"
.br
.ti -1c
.RI "GLubyte \fBindex\fP []"
.br
.in -1c
.SH "Documentación de las variables"
.PP 
.SS "\fBModel\fP g_cube"

.PP
Definición en la línea 5 del archivo Main\&.cpp\&.
.SS "GLubyte index[]"
\fBValor inicial:\fP
.PP
.nf
= { 0, 1, 2, 2, 3, 0, 4, 5, 6, 6, 7, 4, 8, 9, 10, 10, 11, 8, 12,
    13, 14, 14, 15, 12, 16, 17, 18, 18, 19, 16, 20, 21, 22, 22, 23, 20, 24, 25,
    26, 26, 27, 24, 28, 29, 30, 30, 31, 28, 32, 33, 34, 34, 35, 32, 36, 37, 38,
    38, 39, 36, 40, 41, 42, 42, 43, 40, 44, 45, 46, 46, 47, 44 }
.fi
.PP
Definición en la línea 71 del archivo Main\&.cpp\&.
.PP
Referenciado por GLApplication::Initialize()\&.
.SS "\fBVertex3\fP vertices1[]"

.PP
Definición en la línea 8 del archivo Main\&.cpp\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para CubeRubick del código fuente\&.
