.TH "src/Headers/RotationCubeManager.h" 3 "Martes, 26 de Mayo de 2015" "CubeRubick" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Headers/RotationCubeManager.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include 'Model\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <glm/gtx/quaternion\&.hpp>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "struct \fBMovimiento\fP"
.br
.ti -1c
.RI "class \fBRotationCubeManager::RotationCubeManager\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBRotationCubeManager\fP"
.br
.in -1c
.SS "'defines'"

.in +1c
.ti -1c
.RI "#define \fBEPSILON\fP   0\&.000001"
.br
.in -1c
.SH "Documentación de los 'defines'"
.PP 
.SS "#define EPSILON   0\&.000001"

.PP
Definición en la línea 20 del archivo RotationCubeManager\&.h\&.
.PP
Referenciado por RotationCubeManager::RotationCubeManager::RayTriangleIntersect()\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para CubeRubick del código fuente\&.
