.TH "src/RubiksCubeFace.cpp" 3 "Martes, 26 de Mayo de 2015" "CubeRubick" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/RubiksCubeFace.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Headers/RubiksCubeFace\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "float \fBcurrAngle\fP"
.br
.in -1c
.SH "Documentación de las variables"
.PP 
.SS "float currAngle"

.PP
Definición en la línea 10 del archivo RubiksCubeFace\&.cpp\&.
.PP
Referenciado por RubiksCubeFace::rotate()\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para CubeRubick del código fuente\&.
