.TH "src/Headers/RubiksCubeFace.h" 3 "Martes, 26 de Mayo de 2015" "CubeRubick" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Headers/RubiksCubeFace.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./Headers/Node\&.h'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBRubiksCubeFace\fP"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para CubeRubick del código fuente\&.
