.TH "src/CubemapTexture.cpp" 3 "Martes, 26 de Mayo de 2015" "Pistasdeprofunidad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/CubemapTexture.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'Headers/CubemapTexture\&.h'\fP
.br
\fC#include 'Headers/Util\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "static const GLenum \fBtypes\fP [6]"
.br
.in -1c
.SH "Documentación de las variables"
.PP 
.SS "const GLenum types[6]\fC [static]\fP"
\fBValor inicial:\fP
.PP
.nf
= { GL_TEXTURE_CUBE_MAP_POSITIVE_X,
GL_TEXTURE_CUBE_MAP_NEGATIVE_X,
GL_TEXTURE_CUBE_MAP_POSITIVE_Y,
GL_TEXTURE_CUBE_MAP_NEGATIVE_Y,
GL_TEXTURE_CUBE_MAP_POSITIVE_Z,
GL_TEXTURE_CUBE_MAP_NEGATIVE_Z }
.fi
Caras del skydome 
.PP
Definición en la línea 15 del archivo CubemapTexture\&.cpp\&.
.PP
Referenciado por CubemapTexture::Load()\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Pistasdeprofunidad del código fuente\&.
