.TH "src/Main.cpp" 3 "Martes, 26 de Mayo de 2015" "Pistasdeprofunidad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <GL/glew\&.h>\fP
.br
\fC#include 'Headers/Main\&.h'\fP
.br
\fC#include 'Headers/SkyBoxModel\&.h'\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "const glm::vec4 \fBwhite\fP (1)"
.br
.ti -1c
.RI "const glm::vec4 \fBblack\fP (0)"
.br
.ti -1c
.RI "const glm::vec4 \fBambient\fP (0\&.9f, 0\&.9f, 0\&.9f, 1\&.0f)"
.br
.in -1c
.SH "Documentación de las funciones"
.PP 
.SS "const glm::vec4 ambient (0\&.9f, 0\&.9f, 0\&.9f, 1\&.0f)"

.PP
Referenciado por GLApplication::Initialize() y LightingTechnique::SetAttrLight()\&.
.SS "const glm::vec4 black (0)"

.PP
Referenciado por GLApplication::Initialize()\&.
.SS "const glm::vec4 white (1)"

.PP
Referenciado por GLApplication::Initialize()\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Pistasdeprofunidad del código fuente\&.
