.TH "src/Headers/Mesh.h" 3 "Martes, 26 de Mayo de 2015" "Pistasdeprofunidad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Headers/Mesh.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <glm/glm\&.hpp>\fP
.br
\fC#include <glm/gtc/matrix_transform\&.hpp>\fP
.br
\fC#include <glm/gtx/transform2\&.hpp>\fP
.br
\fC#include <assimp/Importer\&.hpp>\fP
.br
\fC#include <assimp/scene\&.h>\fP
.br
\fC#include <assimp/postprocess\&.h>\fP
.br
\fC#include <GL/glew\&.h>\fP
.br
\fC#include 'Texture\&.h'\fP
.br
\fC#include 'Util\&.h'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "struct \fBMesh::Vertex\fP"
.br
.ti -1c
.RI "class \fBMesh::Mesh\fP"
.br
.ti -1c
.RI "struct \fBMesh::Mesh::MeshEntry\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBMesh\fP"
.br
.in -1c
.SS "'defines'"

.in +1c
.ti -1c
.RI "#define \fBINVALID_MATERIAL\fP   0xFFFFFFFF"
.br
.in -1c
.SH "Documentación de los 'defines'"
.PP 
.SS "#define INVALID_MATERIAL   0xFFFFFFFF"

.PP
Definición en la línea 144 del archivo Mesh\&.h\&.
.PP
Referenciado por Mesh::Mesh::MeshEntry::MeshEntry()\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Pistasdeprofunidad del código fuente\&.
