.TH "src/Headers/ModelEnvironment.h" 3 "Martes, 26 de Mayo de 2015" "Pistasdeprofunidad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Headers/ModelEnvironment.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <GL/glew\&.h>\fP
.br
\fC#include <glm/glm\&.hpp>\fP
.br
\fC#include <glm/gtc/matrix_transform\&.hpp>\fP
.br
\fC#include <glm/gtx/transform2\&.hpp>\fP
.br
\fC#include 'LightingTechnique\&.h'\fP
.br
\fC#include 'Camera\&.h'\fP
.br
\fC#include 'Texture\&.h'\fP
.br
\fC#include 'Mesh\&.h'\fP
.br
\fC#include 'CubemapTexture\&.h'\fP
.br
\fC#include 'Model\&.h'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBModelEnvironment\fP"
.br
.in -1c
.SS "'defines'"

.in +1c
.ti -1c
.RI "#define \fBGLM_FORCE_RADIANS\fP"
.br
.in -1c
.SH "Documentación de los 'defines'"
.PP 
.SS "#define GLM_FORCE_RADIANS"

.PP
Definición en la línea 4 del archivo ModelEnvironment\&.h\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Pistasdeprofunidad del código fuente\&.
