.TH "src/Headers/SkyBoxModel.h" 3 "Martes, 26 de Mayo de 2015" "Pistasdeprofunidad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Headers/SkyBoxModel.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include 'Mesh\&.h'\fP
.br
\fC#include 'Shader\&.h'\fP
.br
\fC#include 'Camera\&.h'\fP
.br
\fC#include 'CubemapTexture\&.h'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBSkyBoxModel\fP"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Pistasdeprofunidad del código fuente\&.
