.TH "src/TowerDubai.cpp" 3 "Martes, 26 de Mayo de 2015" "Pistasdeprofunidad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/TowerDubai.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Headers/TowerDubai\&.h'\fP
.br

.SS "'defines'"

.in +1c
.ti -1c
.RI "#define \fBoffset\fP   (float)0\&.025"
.br
.in -1c
.SH "Documentación de los 'defines'"
.PP 
.SS "#define offset   (float)0\&.025"

.PP
Definición en la línea 10 del archivo TowerDubai\&.cpp\&.
.PP
Referenciado por TowerDubai::createLevelsTower()\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Pistasdeprofunidad del código fuente\&.
